### ISSUE TITLE
Client side JavaScript source code

### ISSUE THREAD

**Issue by doughri** [Yubico/java-u2flib-server#11]
Hi,

This lib is used for server side, so what about the client side? how can get data from U2F token before I'll send it to server?
thanks!

**Comment by minisu** [comment]
There's a note in the top of the README saying "Make sure that you have read [Using a U2F library](https://developers.yubico.com/U2F/Libraries/Using_a_library.html) before continuing." The page being linked to has a section called *Client-side*. Have a look there.
