### ISSUE TITLE
JsonMappingException in registration token response 

### ISSUE THREAD

**Issue by doughri** [Yubico/java-u2flib-server#13]
I'm trying to instantiate  RegisterResponse object using the token response using this java code :
RegisterResponse registerResponse = RegisterResponse.fromJson(response);
I get this exception: 
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/JsonMappingException...

Do I have to add others libraries then the u2flib-server-core-0.14.0.jar???

**Comment by minisu** [comment]
Like with most Java libraries, all dependencies are listed in the pom.xml file.
