### ISSUE TITLE
During u2f device registration getting error

### ISSUE THREAD

**Issue by GaneshVarahade** [Yubico/java-u2flib-server#14]
<script>
var request = ${data};
setTimeout(function() {
    u2f.register(request.registerRequests, request.authenticateRequests,
    function(data) {
        var form = document.getElementById('form');
        var reg = document.getElementById('tokenResponse');
        if(data.errorCode) {
            alert("U2F failed with error: " + data.errorCode);
            return;
        }
        reg.value=JSON.stringify(data);
        form.submit();
    });
}, 1000);
</script>

When I am using app id as a String APP_ID = "http://localhost:8888"; then I am getting following error in my JS function during device registration "U2F failed with error: 2".

When I am using app id as a String APP_ID = "https://localhost:8888"; then I am getting SSL connection error during registration device.

**Comment by minisu** [comment]
1. Are you using Chrome on a desktop computer?
2. Are you testing the [u2flib-server-demo](https://github.com/Yubico/java-u2flib-server/tree/master/u2flib-server-demo) server or have you developed your own server that is using u2flib-server-core?

**Comment by GaneshVarahade** [comment]
1. Yes, I using chrome.
2. I have my own code with u2flib-server-core library.

**Comment by minisu** [comment]
Ok, the SSL Connection error has nothing to do with U2F or u2flib-server-core. It's probably caused by misconfiguration in your web server.

**Comment by GaneshVarahade** [comment]
When I am using app id as a String APP_ID = "http://localhost:8888"; then I am getting following error in my JS function during device registration "U2F failed with error: 2".
So can you help what is issue?

**Comment by minisu** [comment]
[Error code 2](https://developers.yubico.com/U2F/Libraries/Client_error_codes.html) is because you're not using HTTPS. Chrome prevents U2F registrations/authentications on unsecure (non-HTTPS) webpages. This means that you have to configure your server for HTTPS to get U2F to work.

While developing/testing, you can use a self-signed certificate (Chrome will give you a warning that you can bypass). For an example of this, see [u2flib-server-demo](https://github.com/Yubico/java-u2flib-server/tree/master/u2flib-server-demo). However, for production you need a certificate signed by a certificate authority (CA).

**Comment by simplenotezy** [comment]
I am getting this error
![image](https://user-images.githubusercontent.com/3786627/27878280-f796e57e-61bd-11e7-8ff6-f5558845830b.png)
Using this code
	@section('content')
			<div id="status">Waiting for user touch</div>
			        <form method="POST" action="finishAuthentication" id="form">
	            <input type="text" name="tokenResponse" id="tokenResponse"/>
	            <input type="text" name="username" id="username" value="${username}"/>
	        </form>
	@endsection

	@section('scripts')		

	<script>
	var request = $;
	setTimeout(function() {
	    u2f.sign(request.authenticateRequests,
	    function(data) {
	        if(data.errorCode) {
	            alert("U2F failed with error code: " + data.errorCode);
	            return;
	        }
	        document.getElementById('tokenResponse').value = JSON.stringify(data);
	        document.getElementById('form').submit();
	    });
	}, 1000);
	</script>

and `u2f.EXTENSION_ID = 'pfboblefjcgdjicmnffhdgionmgcdmne';`

Why?
