### ISSUE TITLE
Unexpected Token { in Example

### ISSUE THREAD

**Issue by Mikekij** [Yubico/java-u2flib-server#15]
First, thanks for making this example library available.

I'm attempting to have my Django app register a Yubikey against the example U2F python server you've provided. When I add the js below into my template, I get the following error:
    
    var request = ${data};

error:
    
    Uncaught SyntaxError: Unexpected token {

This is a silly issue, but I can't quite figure out a workaround. Any suggestions?

**Comment by minisu** [comment]
Not sure what you are saying. Did you take the JavaScript code from [register.ftl](https://github.com/Yubico/java-u2flib-server/blob/master/u2flib-server-demo/src/main/resources/demo/view/register.ftl) (found in this Java library's demo server) and put it in your Django application? If so, register.ftl is a Freemarker template and `${data}` will be replaced (by Freemarker) with the content of the `data` property. In other words, `${data}` is replaced on the server side with the actual registration data. In Django you would do this in a different way.

You should have a look at [django-u2f](https://github.com/gavinwahl/django-u2f) or [python-u2flib-server](https://github.com/Yubico/python-u2flib-server) instead. This is a Java-specific library.
