### ISSUE TITLE
Maven versioning

### ISSUE THREAD

**Issue by jdhoek** [Yubico/java-u2flib-server#17]
Hi! Thanks for sharing this library. It helps to get the server-side of FIDO U2F authentication working.

There is something odd about the versioning used in this Maven project. The version number is always set to the last released version instead of using a `SNAPSHOT` version for intermediate development builds. This means that a `mvn clean install` of the current `HEAD` builds a `0.14.0` version of the library.

To guarantee reproducible builds, I would recommend to only have the tagged release commits use a full version number (e.g., `0.14.0`), and that all intermediate commits are reset to a SNAPSHOT version (e.g., `0.15.0-SNAPSHOT`).

This helps anyone working on your code, because they can create development builds with a SNAPSHOT version. SNAPSHOT dependencies are always updated by Maven if you depend on them during development, whereas full releases (without the `-SNAPSHOT` marker) get cached more aggressively.

I recommend using the [Maven Release Plugin](https://maven.apache.org/maven-release/maven-release-plugin/index.html) to facilitate this workflow.

Feel free to contact me if you have any questions about this topic.

**Comment by jdhoek** [comment]
See also: https://maven.apache.org/guides/getting-started/index.html#What_is_a_SNAPSHOT_version

**Comment by dainnilsson** [comment]
Weird, I'm not quite sure why this project isn't using the release plugin (or why the version hasn't been bumped post-release).

**Comment by jdhoek** [comment]
Might be related to #18.
