### ISSUE TITLE
Can release 0.16.0 be released?

### ISSUE THREAD

**Issue by jdhoek** [Yubico/java-u2flib-server#21]
Would it be possible for a version `0.16.0` containing the recent commits to be released to Maven Central? I don't mind building the library myself, but would like to depend on a released version eventually.

Thanks in advance. :smiley:

**Comment by dainnilsson** [comment]
Eventually yes. Unfortunately I can't give you a ETA for this at the moment as we're busy with other projects and I'm not entirely sure when we'll have the resources to do this. Before releasing 0.16.0 I'd like to at least move to using the maven release plugin. Ideally I'd like to look over a few additional things as well.

**Comment by jdhoek** [comment]
Okay, thanks for the heads up.

Feel free to contact me if you need some assistance configuring a Maven project for releases to Sonatype's OSS repo (for Maven Central).

If it helps, we have a couple of projects that are released to Maven Central as well; perhaps these can be of use as a reference for the Yubico developer tackling this issue:

* A [simple Java library](https://github.com/LableOrg/java-bitsandbytes), which references:
* [Parent POM](https://github.com/LableOrg/maven-parent/blob/master/pom.xml) (this contains all required Maven configuration for Sonatype's OSS repository)

Our work-flow for releasing a version is:

* `mvn release:prepare`
* `mvn release:perform`
* Log on to https://oss.sonatype.org/ and
  * *close* the repository
  * *release* (and *drop*) the repository

I find that this usually takes me five minutes at most.

**Comment by dainnilsson** [comment]
Thanks. We already have other java projects which use a similar setup, so I don't foresee any issues there, it's just a matter of actually doing it.

**Comment by dainnilsson** [comment]
Sorry for the delay, 0.16.0 is now released.
