### ISSUE TITLE
code deployoment

### ISSUE THREAD

**Issue by shwetakharb** [Yubico/java-u2flib-server#27]
Is it possible to deploy the server demo code on any web server?if yes, can I just build a war and deploy on Tomcat else what changes are to be done in the code?

**Comment by emlun** [comment]
Hi, sorry for the late response. I'm afraid the bundled demo server is pretty tightly coupled to the Dropwizard framework, so I don't think it's easy to just repackage it as a `.war` and deploy it in any application server. If you only need to run the demo server with little or no modifications you can simply run the `.jar` anywhere to start up the server.

That said, the demo server in `u2flib-server-demo` is only a thin layer on top of the `u2flib-server-core` API , and all the server logic is in the `Resource` class which is a plain JAX RS resource class except for returning Dropwizard views. You can easily implement your own resource class(es) to your needs using our demo `Resource` as a guide.

Does that answer your questions?

**Comment by emlun** [comment]
I'll close this issue, but please feel free to reopen it if you have any more questions.
