### ISSUE TITLE
Signing a request in JavaScript with u2f.sign gives {errorCode: 4} in chrome but works in Firefox.

### ISSUE THREAD

**Issue by dean-voets-mdc** [Yubico/java-u2flib-server#31]
My company recently bought FIDO U2F Security Keys and we are trying to add authentication via the keys to our admin website. This works in Firefox with the U2F add-on installed but in chrome u2f.sign keeps returning {errorCode: 4}.

Our website is made in Java with the ZK Framework. On server side we use the java-u2flib-server library. We sign the requests on client side using javascript in the zul files using u2f.register and u2f.sign.

To register a key the user first enters name and password and submits. The server creates the RegistrationData and goes to a second page. There, we use javascript function u2f.register. In the callback we send the response with the DeviceRegistration to the server.

The login is done similarly. When submitting the first page the server gives the DeviceRegistration json and a challenge to a second page. The page uses u2f.sign and sends the DeviceResponse to the server in the callback. 

According to the documentation this means the device does not know the received DeviceRegistration but that seems unlikely since the same code works in firefox and I checked that they receive the same json from the server.

Do you know what can cause that or what I can do to debug the problem?

Thanks in advance,
Dean Voets

**Comment by emlun** [comment]
Hi, sorry for the late response. Do you still have this problem, or did you solve it yourself while waiting?

**Comment by dean-voets-mdc** [comment]
Better late then never :D. I got it resolved myself but I don't remember what the problem was. 

If I remember correctly I gave the arguments for U2F version 0.97 to u2f.sign/u2f.register and they were changed in version 1.

**Comment by emlun** [comment]
Ok, good to hear! :) Sounds like we can close this, then?
