### ISSUE TITLE
shouldn't requestStorage be a cache and not userStorage

### ISSUE THREAD

**Issue by Sahasrara** [Yubico/java-u2flib-server#35]
shouldn't requestStorage be a cache and not userStorage?  Seems like the requests would need the time limit and not the userStorage which would presumably be more permanent?

**Comment by emlun** [comment]
Is this about the webauth-server-demo subproject?

In that case: yes, in a real application that's what you'd want to do. But since this is the demo we have deployed on demo.yubico.com/webauthn I chose to have user registrations expire after a while as well.
