### ISSUE TITLE
Getting error while authenticating U2F token with com.yubico 0.18.1

### ISSUE THREAD

**Issue by amitnaik** [Yubico/java-u2flib-server#39]
Hello, we have Yubico tokens but recently we are not able to login to our application. This is the java exception we are getting when we are trying to login with Yubico key. Please help us resolving this problem. I have attached error logs for the same while user attempts to login.
[blackice.log](https://github.com/Yubico/java-u2flib-server/files/3097370/blackice.log)

**Comment by emlun** [comment]
Hi!

Looks like `KeyFactory` doesn't have access to a `BouncyCastleProvider` security provider. This should be set up by the static initializer in [`BouncyCastleCrypto`][bcc], but I suspect that's a bit fragile.

Is this an existing system or a new one in development?

[bcc]: https://github.com/Yubico/java-u2flib-server/blob/master/u2flib-server-core/src/main/java/com/yubico/u2f/crypto/BouncyCastleCrypto.java#L25-L27

**Comment by emlun** [comment]
I pushed an attempt to fix this on branch [`issue-39-ecdsa-keyfactory-not-available`][branch], you're welcome to test if that works for you.

[branch]: https://github.com/Yubico/java-u2flib-server/tree/issue-39-ecdsa-keyfactory-not-available

**Comment by amitnaik** [comment]
Thank you for this fix! Could you please tell me the version for u2flib-server-core version.
Currently we are using **0.18.1**

**Comment by emlun** [comment]
I haven't released the prototype as a versioned release yet. Are you able to try to build branch [`issue-39-ecdsa-keyfactory-not-available`](https://github.com/Yubico/java-u2flib-server/tree/issue-39-ecdsa-keyfactory-not-available) and test if the fix works?

**Comment by amitnaik** [comment]
I have tested this with main method

`public static void main(String[] args) throws Exception {
        Provider provider = new BouncyCastleProvider();
        Signature ecdsaSignature = Signature.getInstance("SHA256withECDSA", provider);

        X9ECParameters curve = SECNamedCurves.getByName("secp256r1");
        ECPoint point = null;

        KeyFactory.getInstance("ECDSA", provider).generatePublic(
                new ECPublicKeySpec(point,
                        new ECParameterSpec(
                                curve.getCurve(),
                                curve.getG(),
                                curve.getN(),
                                curve.getH())));
    }`

**It is now working fine and its not throwing any exceptions**

Requesting you to release this one!

**Comment by emlun** [comment]
Great, thanks! I just pushed version 0.19.3-RC1 into the relase pipeline, it should show up on Maven Central soon. If nothing else comes up in a week I'll promote it to a proper 0.19.3 release.
