### ISSUE TITLE
Your Example does not compile

### ISSUE THREAD

**Issue by steowens** [Yubico/java-u2flib-server#48]
Your demo.Resource file in the u2f-lib-server module fails to compile because one of your exception cases attempts to call a non-existent getDeviceRegistration() method on DeviceCompromisedException

**Comment by emlun** [comment]
Hi! Thanks for letting us know, but we're not going to fix this. This library should not be used for new deployments (they should use [java-webauthn-server](https://github.com/Yubico/java-webauthn-server) instead), and existing ones probably don't need the example anymore.
